### ISSUE TITLE
magic.prime exception

### ISSUE THREAD

**Issue by barryrowlingson** [RobinHankin/magic#2]
`magic.prime` says "Claimed to work for prime order," but:

```
> is.magic(magic.prime(2))
[1] FALSE
> magic.prime(2)
     [,1] [,2]
[1,]    1    4
[2,]    2    3
>
```

and of course 2 is prime!

**Comment by RobinHankin** [comment]
ouch, good catch.  Thanks for this!  Frankly I don't think 2 has any business being prime...
